# Generated by Django 4.2.13 on 2024-06-25 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('orders', '0002_remove_order_product_remove_order_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_created', to='accounts.customuser'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_no',
            field=models.CharField(editable=False, max_length=100, null=True, unique=True),
        ),
    ]
